### PR TITLE
test: Add e2e Tests

### PR DESCRIPTION
**Pull request by eshanvaid**

### CODE REVIEW

**Comment by sandipndev** [comment]
Can you also add the github actions here?

**Comment by eshanvaid** [comment]
>Can you also add the github actions here?

@sandipndev GitHub Actions config is already included in the PR. Please review.

**Comment by sandipndev** [comment]
Awesome!
It’d be good to also add an e2e test for batch now that it’s merged. I’ll let you add it to this PR or a different one, keeping it approved.

**Review by sandipndev — APPROVED** [review]
LGTM!

**Pull request merged**
