### PR TITLE
feat: Add the github workflow for unit tests

### PR DESCRIPTION
**Pull request by SiddheshKanawade**
What does this PR do?
- Add github workflow for unit tests
- Update the version of `graphql_client`
- Add `Cargo.lock` in gitignore as its recommended to ignore Cargo.lock when it keeps track of libraries. Detailed discussion can be found [here](https://github.com/rust-lang/cargo/issues/315)

Signed-off by: SiddheshKanawade [siddhesh.kanawade@iitgn.ac.in](mailto:siddhesh.kanawade@iitgn.ac.in)

### CODE REVIEW

**Comment by SiddheshKanawade** [comment]
@nicolasburtey i have added the workflow for unit tests. Please review the PR and let me know if there is anything else to be done in this

**Comment by SiddheshKanawade** [comment]
@nicolasburtey @sandipndev @bodymindarts could you please approve the github workflow? I just want to check whether the unit tests are passing or not. In my local system, most of the unit tests are failing as respective user can't be found. Following is the stack trace for the same.
```
thread 'batch_cant_pay_self' panicked at 'assertion failed: batch.populate_wallet_id().is_ok()', tests/batch.rs:40:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and below is the query output from [this](https://github.com/GaloyMoney/galoy-cli/blob/main/src/client/batch.rs#L81)
```
Err(Username userA doesn't exist)
```

It seems I need to populate some data in my local system, I have successfully set the Postman for local development using the [documentation](https://github.com/GaloyMoney/galoy/tree/main/docs/postman-collection). I am yet figuring out how to resolve the above issue and add the user to the system, any help is highly appreciated.

System: MacOS M1
Unit test: [batch_cant_pay_self](https://github.com/GaloyMoney/galoy-cli/blob/main/tests/batch.rs#L27)

**Comment by SiddheshKanawade** [comment]
@nicolasburtey @sandipndev I feel this PR can be merged. So that whenever we do some changes to unit tests, we can check here whether that particular test works fine or not. Implementing/Correcting tests can go as part of different PR.

**Comment by sandipndev** [comment]
this PR deletes a lot of important files, actions for testing was added a week back in a different PR.

**Pull request closed without merging**
